version: '3.9'
services:
  sqlserver:
    container_name: db_security
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin.1234"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
